INSERT INTO PRODUCTO (id, nombre, tipo_prod, precio, ruta_img, cantidad_stock, descripcion) VALUES (NEXTVAL('hibernate_sequence'),'Zippo','Mechero', '3', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTK_0Apu3V9FsqLoViVmuyyWprIf54D4-zW3Q&usqp=CAU','5', 'Encendedor a gasolina
de mecanismo de piedra. Clásico diseño de inspiración americana y acabado metálico brillante. Con protección infantil y presentado en caja individual.'); 
INSERT INTO PRODUCTO (id, nombre, tipo_prod, precio, ruta_img,cantidad_stock, descripcion) VALUES (NEXTVAL('hibernate_sequence'),'Cenicero RAW','Cenicero', '2', 'https://www.growlobby.com/media/catalog/product/cache/cb5153ff5220d94d443bd12d0cb817d4/r/a/raw-cenicero-cristal-premium.jpg', '5', 'C Este cenicero esta basado en los ceniceros que habían en los bares de 1950. Una autentica obra de arte para los fumadores mas exclusivos.');
INSERT INTO PRODUCTO (id, nombre, tipo_prod, precio, ruta_img,cantidad_stock, descripcion) VALUES (NEXTVAL('hibernate_sequence'),'Camchimba Aladin','Cachimba', '300', 'https://cdn.shopify.com/s/files/1/0120/9804/4000/products/aladin-mvp-360-rainbow.jpg?v=1592823583', '5', 'EL modelo ALADIN MVP 470 llega en un modelo sencillo y elegante. Un modelo con unas dimensiones perfectas para emplearse tanto en exteriores como en lugares cerrados.'); 
INSERT INTO PRODUCTO (id, nombre, tipo_prod, precio, ruta_img,cantidad_stock, descripcion) VALUES (NEXTVAL('hibernate_sequence'),'Clipper','Mechero', '1.30', 'https://www.regalospublicitarios.com/95711-thickbox_default/mechero-clipper-pocket.jpg', '5', 'Mechero Clipper Large a gas, de mecanismo de piedra.'); 
INSERT INTO PRODUCTO (id, nombre, tipo_prod, precio, ruta_img,cantidad_stock, descripcion) VALUES (NEXTVAL('hibernate_sequence'),'Vape Swag','Vape', '150', 'https://m.media-amazon.com/images/I/51wfx57c2OL._AC_SX466_.jpg', '5', 'El Vaporesso Swag 2 incorpora AXON CHIP que ofrece un increíble modo pulse, que es capaz de ofrecer hasta 5 veces más potencia en cada calada. '); 
INSERT INTO PRODUCTO (id, nombre, tipo_prod, precio, ruta_img,cantidad_stock, descripcion) VALUES (NEXTVAL('hibernate_sequence'),'Sisha MrShisha','Cachimba', '430', 'https://www.mrshisha.es/697-large_default/mr-shisha-rocket-20-turquise-resin.jpg', '5', 'Espectacular cachimba Mr. Shisha Rocket, una cachimba de tamaño pequeño con base de cristal tranparente con 1cm de grosor de fondo, camara tradicional y purga completamente renovada.');
INSERT INTO PRODUCTO (id, nombre, tipo_prod, precio, ruta_img,cantidad_stock, descripcion) VALUES (NEXTVAL('hibernate_sequence'),'Vape Stick V8','Vape', '100', 'https://m.media-amazon.com/images/I/51Z6T1FhebL._AC_SL1001_.jpg', '5', 'Kit estilo AIO de la marca Smok formado por la batería Stick V8 y el atomizador TFV8 Big Baby Beast.'); 
INSERT INTO PRODUCTO (id, nombre, tipo_prod, precio, ruta_img,cantidad_stock, descripcion) VALUES (NEXTVAL('hibernate_sequence'),'Cachimba Moze','Cachimba', '250', 'https://www.originshisha.com/13987-large_default/cachimba-moze-x-vyro-noir.jpg', '5', 'La alemana Moze nos trae la nueva Moze Breeze Two Wavy Pink, una cachimba llamativa, cuyos detalles imitan al hielo.'); 
INSERT INTO PRODUCTO (id, nombre, tipo_prod, precio, ruta_img,cantidad_stock, descripcion) VALUES (NEXTVAL('hibernate_sequence'),'Mechero Bunsen','Mechero', '10', 'https://esp.labbox.com/wp-content/uploads/sites/2/2020/07/BUNS-B03-001.jpg', '5', 'Mechero bunsen con base cromada y entradas de aire ajustables.'); 
INSERT INTO PRODUCTO (id, nombre, tipo_prod, precio, ruta_img,cantidad_stock, descripcion) VALUES (NEXTVAL('hibernate_sequence'),'Cachimba Steamulation','Cachimba', '150', 'https://www.medusashishashop.com/wp-content/uploads/2021/03/Steamulation-PRO-X-Black.jpg', '5', 'La serie Steamulation Pro X permite a los fumadores experimentados de cachimba personalizar completamente su experiencia de fumar.'); 
INSERT INTO PRODUCTO (id, nombre, tipo_prod, precio, ruta_img,cantidad_stock, descripcion) VALUES (NEXTVAL('hibernate_sequence'),'Cenicero Naruto','Cenicero', '5', 'https://monseart.cl/wp-content/uploads/2021/10/Cenicero-akatsuki.png', '5', 'Está hecho de arcilla, pintado con acrílico y cubierto de resina.'); 
INSERT INTO PRODUCTO (id, nombre, tipo_prod, precio, ruta_img,cantidad_stock, descripcion) VALUES (NEXTVAL('hibernate_sequence'),'Mechero Básico','Mechero', '1', 'https://regalosvarios.com/5476-large_default/mechero-encendedor.jpg', '5', 'Mechero encendedor recargable.'); 
INSERT INTO PRODUCTO (id, nombre, tipo_prod, precio, ruta_img,cantidad_stock, descripcion) VALUES (NEXTVAL('hibernate_sequence'),'Cenicero Aguacate','Cenicero', '2.50', 'https://cdn.shopify.com/s/files/1/0080/5791/3425/products/FISURA_HM1216_1024x1024.jpg?v=1584396316', '5', '¡Para los que saben que el aguacate también es un vicio!'); 
INSERT INTO PRODUCTO (id, nombre, tipo_prod, precio, ruta_img,cantidad_stock, descripcion) VALUES (NEXTVAL('hibernate_sequence'),'Zippo Métalico','Mechero', '4', 'https://laesquina.es/wp-content/uploads/2021/08/zippo-ace-skull-design-001.jpg', '5', 'Encendedor a gasolina metálico con mecanismo de piedra.'); 